import { apiClient, sendRequestWithRetry } from './ApiClient';

// Existing function for Java service
export const randomGenerated = (randomNumber) => {
    return apiClient.post('/distributed-sort-autogenerated', {
        randomNumber: parseInt(randomNumber, 10)
    });
};

export const addNumbers = (numbers) => {
    return apiClient.post('/add-numbers', numbers);
};

// Loadbalancer Approach with Retry
export const loadRandomGenerated = (randomNumber) => {
    return sendRequestWithRetry({
        url: '/distributed-sort-autogenerated',
        method: 'post',
        data: {
            randomNumber: parseInt(randomNumber, 10)
        }
    });
};

export const loadAddNumbers = (numbers) => {
    return sendRequestWithRetry({
        url: '/add-numbers',
        method: 'post',
        data: numbers
    });
};
